### ISSUE TITLE
Can we only look at one type at once?

### ISSUE THREAD

**Issue by titanlien** [rekuberate-io/sleepcycles#20]
I would like to control the cronjob, however, I would like skip/ignore deployment/statefulset/HPA manifest. How can we do that?

**Comment by akyriako** [comment]
Hi @titanlien, you can skip **any** resource you wish. The sleepcycle is enabled **only** if you add the `rekuberate.io/sleepcycle` label in the resource you want to control (in your case a cronjob). The rest of your resources will be unaffected; there is no separate manifest per CR. Check the [README.md/How It works](https://github.com/rekuberate-io/sleepcycles/blob/main/README.md#how-it-works) for more details.
